/* Generated by Cython 0.29.13 */

#ifndef __PYX_HAVE__neutron__ccore
#define __PYX_HAVE__neutron__ccore


#ifndef __PYX_HAVE_API__neutron__ccore

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C struct __pyx_obj_7neutron_5ccore_SineWave *sinewave;

#endif /* !__PYX_HAVE_API__neutron__ccore */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initccore(void);
#else
PyMODINIT_FUNC PyInit_ccore(void);
#endif

#endif /* !__PYX_HAVE__neutron__ccore */
