#!/usr/bin/env python
# *-* coding: utf-8 *-*
# Author: Thomas Martin <thomas.martin.1@ulaval.ca> 
# File: explorer

import sys, os

from argparse import ArgumentParser
import argparse

import pulsar.sitelle

###########################################
### MAIN ##################################
###########################################
    
def main(args):

    cube = pulsar.sitelle.Cube(args.path)
    #sample = pulsar.sampler.Sample(cube.get_samples(950,850,10))
    #sample.save('test.wav')
    #sample.apply('resample', 0.2)
    #sample.play()
    cube.show()

                
            

if __name__ == "__main__":

    parser = ArgumentParser(description=
                            "SITELLE cube explorer")
    
    parser.add_argument('path', help='Path to an HDF5 cube.')
 
    args = parser.parse_args()

    main(args)
        

